/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: asimazizov5 (https://sketchfab.com/asimazizov5)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blender-logo-60facedcd4a04f18adff4225f017a3c5
Title: Blender Logo
*/

import React from 'react'
import { Float, useGLTF } from '@react-three/drei'

const Blender = (props) => {
  const { nodes, materials } = useGLTF('/models/blender_logo.glb  ')
  return (
    <Float floatingRange={1} speed={1} rotationIntensity={1} floatIntensity={1}>
      <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials['Material.001']}
        position={[-0.182, -0.099, 0]}
        rotation={[1.566, 0.127, 0.001]}
        scale={0.146}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials['Material.002']}
        position={[-0.182, -0.099, 0]}
        rotation={[1.566, 0.127, 0.001]}
        scale={0.223}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials['Material.003']}
        position={[-0.182, -0.099, 0]}
        rotation={[1.566, 0.127, 0.001]}
        scale={0.378}
      />
    </group>
    </Float>
  )
}

useGLTF.preload('/models/blender_logo.glb')

export default Blender;
